name: Generate Snake

on:
  schedule:
    # every 6 hours
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Generate the snake files
        uses: Platane/snk@v3
        id: snake-gif
        with:
          github_user_name: vinayaky7
          gif_out_path: dist/github-contribution-grid-snake.gif
          svg_out_path: dist/github-contribution-grid-snake.svg

      - name: Show build status
        run: git status

      - name: Push changes
        uses: github-push-action/github-push-action@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          force: true

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: output
          folder: dist
