name: Generate GitHub Contribution Graph

on:
  # Run automatically every 12 hours
  schedule:
    - cron: "0 */12 * * *"
  
  # Allows manual run of the job at any time
  workflow_dispatch:
  
  # Run on every push on the main branch
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Ensure dist directory exists
        run: mkdir -p dist

      - name: Set execute permission for script
        run: chmod +x generate_snake_svg_script.sh

      - name: Generate GitHub contribution graph snake SVG
        run: ./generate_snake_svg_script.sh > ./dist/github-contribution-grid-snake.svg

      - name: Push changes to GitHub
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
