name: Snake Animation

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Generate snake (Replace with your custom script)
        run: |
          echo "Generate snake animation script here"
      - name: Commit and push if changed
        run: |
          git config --global user.email "githubaction@users.noreply.github.com"
          git config --global user.name "GitHub Action"
          git add .
          git diff --quiet && git diff --staged --quiet || git commit -m "Update GitHub Contribution Snake" && git push
