name: Generate Animation and Push

on:
  schedule:
    - cron: "0 */12 * * *"  # Runs automatically every 12 hours
  workflow_dispatch:        # Allows manual run
  push:
    branches:
      - main               # Runs on push to main branch

jobs:
  generate:
    runs-on: ubuntu-latest  # Runs on Ubuntu latest version

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Ensure dist directory exists
        run: mkdir -p dist   # Create 'dist' directory if it doesn't exist

      - name: Generate GitHub contribution graph snake SVG
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: vinayaky7
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Commit and push changes to GitHub
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add dist/
          git commit -m "Update GitHub contribution graph snake SVG"
          git pull origin main  # Pull latest changes from main branch
          git push origin main  # Push changes to main branch
