name: Generate Animation

on:
  # Run automatically every 12 hours
  schedule:
    - cron: "0 */12 * * *"
  
  # Allows manual run of the job at any time
  workflow_dispatch:
  
  # Run on every push on the main branch
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2
      
      # Clone Platane/snk repository
      - name: Clone Platane/snk repository
        run: git clone https://github.com/Platane/snk.git ./snk
      
      # Navigate to snk directory
      - name: Navigate to snk directory
        run: cd snk
      
      # Install dependencies (if any)
      - name: Install dependencies (if any)
        run: |
          # Example command to install dependencies (if required)
          # npm install
      
      # Generate the GitHub contribution graph snake SVG
      - name: Generate GitHub contribution graph snake SVG
        run: |
          # Example command to generate snake SVG
          # Replace this with your actual command to generate SVG
          echo "Generating GitHub contribution graph snake SVG..."
          ./path/to/your/snake-generator-script.sh > ./dist/github-contribution-grid-snake.svg
      
      # Push the generated files to the output branch
      - name: Push to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./dist
