name: Generate GitHub Contribution Graph

on:
  # Run automatically every 12 hours
  schedule:
    - cron: "0 */12 * * *"
  
  # Allows manual run of the job at any time
  workflow_dispatch:
  
  # Run on every push on the main branch
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Ensure dist directory exists
        run: mkdir -p dist

      - name: Set execute permission for script
        run: chmod +x generate_snake_svg_script.sh

      - name: Generate GitHub contribution graph snake SVG
        run: |
          echo "Generating GitHub contribution graph snake SVG..."
          ./generate_snake_svg_script.sh > ./dist/github-contribution-grid-snake.svg

      - name: Configure Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Commit and push changes
        run: |
          git checkout -b output
          git add ./dist
          git commit -m "Update GitHub contribution graph snake SVG"
          git push origin output
